title: Innovación precios y dinámica industrial. Un modelo computacional de dos sectores.
description: Trabajo Fin de Master. Master en Economía Universidad de Zaragoza 2017 - 2018. Jorge Casinos
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
